### ISSUE TITLE
how to calculate the measurement matrix H, especially the Hq?

### ISSUE THREAD

**Issue by Happyjie1993** [skrogh/msf_ekf#1]
Thanks a lot about your this contribution. I have a problem on the formula (3.46) in stephan M.weiss doctor paper "vision based navigation for micro helicopters", that is how to calculate the measurement matrix H, especially the part of the Hq? Although i have read your code 
`H_q <<
            Matrix3d::Zero(),
            Matrix3d::Zero(),
            C_q_c_i,
            Matrix3d::Zero(),
            Matrix3d::Zero(),
            Vector3d::Zero(),
            Matrix3d::Zero(),
            Matrix3d::Identity(),
            Matrix3d::Zero(),
            C_q_c_i*C_q_i_w;`
i can't get the formula derivation. I would appreciate it very much if i can obtain any hints from you.

**Comment by skrogh** [comment]
Ah yes this was a bit of a pain, due to the particularization of the "error quaternion".
Note that the implementation is far from thoroughly tested, especially I'm a bit wary if all the quaternion equations are correct, as the paper does not indicate that they in fact redefine quaternions, compared to the original formulation.

Anyway, I did the calculations mostly by hand, with some Matlab assist on big matrices.
I have attached a PDF. It's handwritten, so I hope you will not have too much trouble reading it.
[Deraviation of Hq.pdf](https://github.com/skrogh/msf_ekf/files/159863/Deraviation.of.Hq.pdf)
