### ISSUE TITLE
How we get the dist in the imuData_t

### ISSUE THREAD

**Issue by qiuyeqiang** [skrogh/msf_ekf#3]
i can get the omega_m data and a_m data  from IMU,but how can i get the dist data? what do you mean horizontal distance to ground?

**Comment by skrogh** [comment]
The Quad Rotor that I implemented the system on has a downward facing ultrasonic distance sensor.

While the scaling factor for the camera is strictly speaking observable when acceleration is non-zero, having occasional absolute position measurements helps a great deal with convergence of the scaling factor (I think I named it lambda).

Do note that it's been a while since I last had a look at the code. As I recall the main branch does not work so well, the "alternateParametrization" branch is the most up-to-date. The difference being the representation of attitude.

**Comment by qiuyeqiang** [comment]
What is "alternateParametrization" ? Could you tell me where I can find it?

**Comment by skrogh** [comment]
I'ts the name of a branch: https://github.com/skrogh/msf_ekf/tree/alternateParamtrization
As I said it's simply another way of representing the attitude. Still quaternions, one of the parametrizations is from world to inertial frame, the other is inertial frame to world.

**Comment by qiuyeqiang** [comment]
Thank for your reply, it help me a lot. 
the last question,could you tell me the function of the filter.setCalibration, is it the calibration of IMU? what's the parameter mean like sq_sigma_omega  and sq_sigma_b_omega?

**Comment by skrogh** [comment]
omega is the angular rate.

As I recall it, sq_sigma_omega is the variance of the gyro measurement that is used as input to state propagation. sq_sigma_b_omega is the same for the bias term of the gyro (read: squared sigma b omega, where b stands for bias)

**Comment by qiuyeqiang** [comment]
you mean the variance of the gyro measurement with no movement？

**Comment by skrogh** [comment]
Variance of the measurement noise, yeah.
there should be an sq_sigma_a or sq_sigma_acceleration parameter or something like that, that has the same function for the accelerometer measurements.
